name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 6.0.1
homepage: https://github.com/fluttercandies/extended_image
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  extended_image_library:
    git:
      https://github.com/laoyi168/extended_image_library-3.1.1.git

